"""
sma_squeeze_bt.py - SMA Squeeze Play strategy grid search backtest.
Data: 1h and 4h CSV from DATA_DIR (4h generated by make_4h_from_1h.py).
Output: optimizer/sma_squeeze_bt_result.csv
"""

import itertools
import os
import warnings
from pathlib import Path

import numpy as np
import pandas as pd

warnings.filterwarnings('ignore')

DATA_DIR   = r'C:\Users\Administrator\fx_bot\data'
OUTPUT_DIR = Path(__file__).parent
OUTPUT_CSV = str(OUTPUT_DIR / 'sma_squeeze_bt_result.csv')

PAIRS = ['USDJPY', 'GBPJPY', 'EURUSD', 'GBPUSD', 'EURJPY']

GRID = {
    'sma_short':           [15, 20, 25],
    'sma_long':            [150, 200, 250],
    'squeeze_th':          [0.5, 1.0, 1.5, 2.0],
    'sma200_slope_period': [5, 10, 20],
    'rr':                  [1.5, 2.0, 2.5],
    'sl_atr_mult':         [1.0, 1.5, 2.0],
    'timeframe':           ['1h', '4h'],
}

MIN_TRADES = 30


def load_csv(pair, tf):
    tf_map = {
        '1h': [f'{pair}_1h.csv', f'{pair}_H1.csv', f'{pair}_1H.csv', f'{pair.lower()}_1h.csv'],
        '4h': [f'{pair}_4h.csv', f'{pair}_H4.csv', f'{pair}_4H.csv'],
    }
    candidates = tf_map.get(tf, [f'{pair}_{tf}.csv'])
    for fname in candidates:
        path = os.path.join(DATA_DIR, fname)
        if not os.path.exists(path):
            continue
        df = pd.read_csv(path, index_col=0)
        df.index = pd.to_datetime(df.index)
        try:
            df.index = df.index.tz_convert(None)
        except Exception:
            try:
                df.index = df.index.tz_localize(None)
            except Exception:
                pass
        df.columns = [c.lower() for c in df.columns]
        keep = [c for c in ['open', 'high', 'low', 'close', 'volume'] if c in df.columns]
        df = df[keep].loc[:, ~df.columns.duplicated()]
        df = df.dropna(subset=['close']).sort_index().reset_index(drop=True)
        return df
    return None


def calc_atr14(df):
    hl = df['high'] - df['low']
    hc = (df['high'] - df['close'].shift()).abs()
    lc = (df['low']  - df['close'].shift()).abs()
    tr = pd.concat([hl, hc, lc], axis=1).max(axis=1)
    return tr.rolling(14).mean()


def calc_adx14(df):
    high, low, close = df['high'], df['low'], df['close']
    plus_dm  = high.diff()
    minus_dm = low.diff().mul(-1)
    plus_dm  = plus_dm.where((plus_dm > minus_dm) & (plus_dm > 0), 0.0)
    minus_dm = minus_dm.where((minus_dm > plus_dm) & (minus_dm > 0), 0.0)
    hl       = high - low
    hc       = (high - close.shift()).abs()
    lc       = (low  - close.shift()).abs()
    tr       = pd.concat([hl, hc, lc], axis=1).max(axis=1)
    atr_s    = tr.ewm(alpha=1/14, min_periods=14, adjust=False).mean()
    plus_di  = 100 * plus_dm.ewm(alpha=1/14, min_periods=14, adjust=False).mean() / atr_s.replace(0, np.nan)
    minus_di = 100 * minus_dm.ewm(alpha=1/14, min_periods=14, adjust=False).mean() / atr_s.replace(0, np.nan)
    dx       = 100 * (plus_di - minus_di).abs() / (plus_di + minus_di).replace(0, np.nan)
    return dx.ewm(alpha=1/14, min_periods=14, adjust=False).mean()


def calc_max_dd(equity):
    eq   = np.array(equity, dtype=float)
    peak = np.maximum.accumulate(eq)
    dd   = float((eq - peak).min())
    return -dd if dd < 0 else 0.0


def run_backtest(df, sma_short, sma_long, squeeze_th, slope_period, rr, sl_atr_mult):
    """
    Run single-parameter backtest on df.
    Returns metrics dict or None if n_trades < MIN_TRADES.
    """
    close_s = df['close']
    sma_s   = close_s.rolling(sma_short).mean().values
    sma_l   = close_s.rolling(sma_long).mean().values
    atr14   = calc_atr14(df).values
    adx14   = calc_adx14(df).values
    close_a = close_s.values
    open_a  = df['open'].values
    n       = len(df)

    warmup   = max(sma_long, slope_period, 28) + 2
    trades   = []
    equity   = [0.0]
    in_trade = False
    t_dir = t_entry = t_sl = t_tp = 0.0

    for i in range(warmup, n):
        c     = close_a[i]
        o     = open_a[i]
        sl_v  = sma_l[i]
        ss_v  = sma_s[i]
        atr_v = atr14[i]
        adx_v = adx14[i]

        if np.isnan(sl_v) or np.isnan(ss_v) or np.isnan(atr_v) or np.isnan(adx_v):
            continue

        if in_trade:
            # force close: SMA200 break in opposite direction (priority)
            force = (t_dir == 'long' and c < sl_v) or (t_dir == 'short' and c > sl_v)
            if force:
                pnl = (c - t_entry) if t_dir == 'long' else (t_entry - c)
                trades.append(pnl)
                equity.append(equity[-1] + pnl)
                in_trade = False
            elif t_dir == 'long':
                if c <= t_entry - t_sl:
                    trades.append(-t_sl)
                    equity.append(equity[-1] - t_sl)
                    in_trade = False
                elif c >= t_entry + t_tp:
                    trades.append(t_tp)
                    equity.append(equity[-1] + t_tp)
                    in_trade = False
            else:  # short
                if c >= t_entry + t_sl:
                    trades.append(-t_sl)
                    equity.append(equity[-1] - t_sl)
                    in_trade = False
                elif c <= t_entry - t_tp:
                    trades.append(t_tp)
                    equity.append(equity[-1] + t_tp)
                    in_trade = False

        if in_trade:
            continue

        # common filters
        if adx_v <= 20.0:
            continue
        if sl_v == 0.0:
            continue

        div_rate = abs(ss_v - sl_v) / sl_v * 100.0
        if div_rate > squeeze_th:
            continue

        slp_start = i - slope_period + 1
        if slp_start < 0:
            continue
        slp = sma_l[slp_start: i + 1]
        if np.any(np.isnan(slp)):
            continue

        diffs   = np.diff(slp)
        rising  = bool(np.all(diffs > 0))
        falling = bool(np.all(diffs < 0))
        if not (rising or falling):
            continue

        prev_c = close_a[i - 1]
        prev_s = sma_s[i - 1]
        if np.isnan(prev_s) or np.isnan(prev_c):
            continue

        sl_dist = atr_v * sl_atr_mult
        tp_dist = sl_dist * rr
        if sl_dist == 0.0:
            continue

        if rising and c > sl_v and prev_c < prev_s and c > ss_v and c > o:
            t_dir = 'long'; t_entry = c; t_sl = sl_dist; t_tp = tp_dist
            in_trade = True
        elif falling and c < sl_v and prev_c > prev_s and c < ss_v and c < o:
            t_dir = 'short'; t_entry = c; t_sl = sl_dist; t_tp = tp_dist
            in_trade = True

    if in_trade:
        c   = close_a[-1]
        pnl = (c - t_entry) if t_dir == 'long' else (t_entry - c)
        trades.append(pnl)
        equity.append(equity[-1] + pnl)

    if len(trades) < MIN_TRADES:
        return None

    arr  = np.array(trades)
    wins = arr[arr > 0]
    loss = arr[arr <= 0]
    gp   = float(wins.sum()) if len(wins) > 0 else 0.0
    gl   = float(abs(loss.sum())) if len(loss) > 0 else 0.0
    pf   = gp / gl if gl > 0 else (9.99 if gp > 0 else 0.0)

    return {
        'PF':       round(pf, 3),
        'win_rate': round(len(wins) / len(arr), 3),
        'n_trades': len(arr),
        'max_dd':   round(calc_max_dd(equity), 6),
    }


def main():
    combos = list(itertools.product(
        GRID['sma_short'], GRID['sma_long'], GRID['squeeze_th'],
        GRID['sma200_slope_period'], GRID['rr'], GRID['sl_atr_mult'],
        GRID['timeframe'],
    ))
    total = len(PAIRS) * len(combos)
    print(f'[INFO] {len(PAIRS)} pairs x {len(combos)} combos = {total} runs')

    df_cache = {}
    for pair in PAIRS:
        for tf in GRID['timeframe']:
            df = load_csv(pair, tf)
            df_cache[(pair, tf)] = df
            status = f'{len(df)} rows' if df is not None else 'NOT FOUND'
            print(f'[INFO] {pair} {tf}: {status}')

    all_results = []
    done        = 0

    for pair in PAIRS:
        pair_rows = []
        for sma_short, sma_long, squeeze_th, slope_period, rr, sl_atr_mult, tf in combos:
            done += 1
            if done % 1000 == 0:
                print(f'  progress: {done}/{total}')
            df = df_cache.get((pair, tf))
            if df is None:
                continue
            m = run_backtest(df, sma_short, sma_long, squeeze_th, slope_period, rr, sl_atr_mult)
            if m is None:
                continue
            row = {
                'pair':         pair,
                'timeframe':    tf,
                'sma_short':    sma_short,
                'sma_long':     sma_long,
                'squeeze_th':   squeeze_th,
                'slope_period': slope_period,
                'rr':           rr,
                'sl_atr_mult':  sl_atr_mult,
                'PF':           m['PF'],
                'win_rate':     m['win_rate'],
                'n_trades':     m['n_trades'],
                'max_dd':       m['max_dd'],
            }
            pair_rows.append(row)
            all_results.append(row)

        pair_rows.sort(key=lambda x: x['PF'], reverse=True)
        print(f'\n=== Top 3: {pair} ===')
        for r in pair_rows[:3]:
            print(f"  PF={r['PF']:.3f}  WR={r['win_rate']:.1%}  n={r['n_trades']}"
                  f"  tf={r['timeframe']}  sma={r['sma_short']}/{r['sma_long']}"
                  f"  sq={r['squeeze_th']}  slp={r['slope_period']}"
                  f"  rr={r['rr']}  sl_mult={r['sl_atr_mult']}")
        if not pair_rows:
            print(f'  (no results with n_trades >= {MIN_TRADES})')

    if all_results:
        df_out = (pd.DataFrame(all_results)
                    .sort_values('PF', ascending=False)
                    .reset_index(drop=True))
        df_out.to_csv(OUTPUT_CSV, index=False)
        print(f'\n[INFO] {len(df_out)} rows saved -> {OUTPUT_CSV}')
    else:
        print('[WARN] no results found')


if __name__ == '__main__':
    main()
